DEBUG = true
USE_LLM = false

MAX_OBJECT_CYCLES = 3
MAX_OUTPUT_SELECTOR_DEPTH = 3
HARD_CUTOFF_DEPTH = 12
MAX_INPUT_DEPTH = 12

USE_OBJECTS_BUCKET = true
USE_DEPENDENCY_GRAPH = true
NO_DATA_COUNT_AS_SUCCESS = false
DISABLE_MUTATIONS = false

ALLOW_DELETION_OF_OBJECTS = false
MAX_FUZZING_ITERATIONS = 1
MAX_TIME = 60
SKIP_MAXIMAL_PAYLOADS = true
SKIP_DOS_ATTACKS = true
SKIP_INJECTION_ATTACKS = true
SKIP_MISC_ATTACKS = true

REQUEST_TIMEOUT = 15
TIME_BETWEEN_REQUESTS = 0.001

SKIP_NODES = []

[CUSTOM_HEADERS]
Accept = "application/json"
